"""Analytics models: weekly reviews, monthly reports, predictions, achievements."""

from __future__ import annotations

import uuid
from datetime import date
from decimal import Decimal
from enum import Enum

from sqlalchemy import Boolean, Date, ForeignKey, Integer, Numeric, String, Text
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin, UUIDMixin


class AchievementType(str, Enum):
    WEIGHT_MILESTONE = "weight_milestone"
    WORKOUT_STREAK = "workout_streak"
    SWIM_MILESTONE = "swim_milestone"
    PERSONAL_RECORD = "personal_record"
    CONSISTENCY = "consistency"
    NUTRITION = "nutrition"
    SLEEP = "sleep"
    SPECIAL = "special"


class WeeklyReview(UUIDMixin, TimestampMixin, Base):
    """
    Weekly coaching report generated every Sunday by the Reflection Agent.

    Captures subjective and objective data for the past 7 days.
    Used as input for plan adjustments and long-term trend analysis.
    """

    __tablename__ = "weekly_reviews"

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    week_start_date: Mapped[date] = mapped_column(Date, nullable=False, index=True)
    week_end_date: Mapped[date] = mapped_column(Date, nullable=False)

    # Objective data (from logs)
    start_weight_kg: Mapped[Decimal | None] = mapped_column(Numeric(5, 2))
    end_weight_kg: Mapped[Decimal | None] = mapped_column(Numeric(5, 2))
    weight_change_kg: Mapped[Decimal | None] = mapped_column(Numeric(4, 2))
    gym_sessions_completed: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    gym_sessions_planned: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    swim_sessions_completed: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    swim_sessions_planned: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    avg_daily_calories: Mapped[int | None] = mapped_column(Integer)
    avg_daily_protein_g: Mapped[int | None] = mapped_column(Integer)
    avg_sleep_hours: Mapped[Decimal | None] = mapped_column(Numeric(3, 1))

    # Subjective ratings (1-10)
    energy_rating: Mapped[int | None] = mapped_column(Integer)
    sleep_quality_rating: Mapped[int | None] = mapped_column(Integer)
    stress_rating: Mapped[int | None] = mapped_column(Integer)
    motivation_rating: Mapped[int | None] = mapped_column(Integer)
    pain_rating: Mapped[int | None] = mapped_column(Integer)

    # AI analysis
    overall_score: Mapped[int | None] = mapped_column(Integer)  # 0-100
    ai_coaching_report: Mapped[str | None] = mapped_column(Text)
    wins: Mapped[list] = mapped_column(JSONB, default=list)
    areas_for_improvement: Mapped[list] = mapped_column(JSONB, default=list)
    next_week_adjustments: Mapped[dict] = mapped_column(JSONB, default=dict)
    photos_uploaded: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    user: Mapped = relationship("User", back_populates="weekly_reviews")

    def __repr__(self) -> str:
        return f"<WeeklyReview week={self.week_start_date}>"


class MonthlyReport(UUIDMixin, TimestampMixin, Base):
    """Monthly progress summary generated by the Analytics Agent."""

    __tablename__ = "monthly_reports"

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    month: Mapped[int] = mapped_column(Integer, nullable=False)
    year: Mapped[int] = mapped_column(Integer, nullable=False)

    # Aggregate metrics
    total_gym_sessions: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    total_swim_sessions: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    gym_adherence_pct: Mapped[Decimal | None] = mapped_column(Numeric(5, 2))
    swim_adherence_pct: Mapped[Decimal | None] = mapped_column(Numeric(5, 2))
    nutrition_adherence_pct: Mapped[Decimal | None] = mapped_column(Numeric(5, 2))
    avg_weight_kg: Mapped[Decimal | None] = mapped_column(Numeric(5, 2))
    weight_change_kg: Mapped[Decimal | None] = mapped_column(Numeric(4, 2))
    body_fat_change_pct: Mapped[Decimal | None] = mapped_column(Numeric(3, 1))

    ai_summary: Mapped[str | None] = mapped_column(Text)
    highlights: Mapped[list] = mapped_column(JSONB, default=list)
    metrics_breakdown: Mapped[dict] = mapped_column(JSONB, default=dict)

    def __repr__(self) -> str:
        return f"<MonthlyReport {self.year}-{self.month:02d}>"


class Prediction(UUIDMixin, TimestampMixin, Base):
    """
    AI-generated predictions (weight on event date, body fat at target date, etc.).

    Recalculated weekly by the Analytics Agent based on current trends.
    Historical predictions are kept to evaluate model accuracy over time.
    """

    __tablename__ = "predictions"

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    prediction_type: Mapped[str] = mapped_column(String(100), nullable=False)
    target_date: Mapped[date] = mapped_column(Date, nullable=False, index=True)
    predicted_value: Mapped[Decimal] = mapped_column(Numeric(8, 2), nullable=False)
    unit: Mapped[str] = mapped_column(String(50), nullable=False)
    confidence_pct: Mapped[Decimal | None] = mapped_column(Numeric(5, 2))
    methodology: Mapped[str | None] = mapped_column(Text)
    actual_value: Mapped[Decimal | None] = mapped_column(Numeric(8, 2))

    def __repr__(self) -> str:
        return f"<Prediction {self.prediction_type}={self.predicted_value} on {self.target_date}>"


class Achievement(UUIDMixin, TimestampMixin, Base):
    """Milestone and achievement badges for the user."""

    __tablename__ = "achievements"

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    achievement_type: Mapped[AchievementType] = mapped_column(String(50), nullable=False)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    icon: Mapped[str | None] = mapped_column(String(100))
    achieved_on: Mapped[date] = mapped_column(Date, nullable=False)
    achievement_metadata: Mapped[dict] = mapped_column(JSONB, default=dict)

    user: Mapped = relationship("User", back_populates="achievements")
