"""
Chat API — the primary interface for conversing with FitnessOS.

All AI coaching interactions flow through this endpoint.
Supports both streaming and non-streaming responses.
"""

from __future__ import annotations

import uuid
from typing import AsyncGenerator

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
from sqlalchemy.ext.asyncio import AsyncSession

from app.agents.graph import run_agent_pipeline
from app.core.security import TokenPayload, get_current_user
from app.db.session import get_db
from app.core.logging import get_logger, bind_request_context

logger = get_logger("api.chat")
router = APIRouter(prefix="/chat", tags=["Chat"])


class ChatRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=10000)
    session_id: str | None = Field(None, description="Continue an existing conversation")
    stream: bool = Field(False, description="Stream the response token by token")


class ChatResponse(BaseModel):
    response: str
    session_id: str
    agent_trace: list[str] = []
    follow_up_suggestions: list[str] = []
    confidence_score: float | None = None
    request_id: str


@router.post("/message", response_model=ChatResponse)
async def send_message(
    request: ChatRequest,
    current_user: TokenPayload = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> ChatResponse:
    """
    Send a message to FitnessOS and receive a personalized coaching response.

    The response is generated by the multi-agent pipeline which:
    1. Loads all relevant memory and context
    2. Routes to specialist agents as needed
    3. Synthesizes a comprehensive coaching response
    4. Stores new memories from the conversation
    """
    session_id = request.session_id or str(uuid.uuid4())
    request_id = str(uuid.uuid4())

    bind_request_context(
        request_id=request_id,
        user_id=current_user.sub,
        path="/api/v1/chat/message",
    )

    logger.info("Chat request received", session_id=session_id)

    final_state = await run_agent_pipeline(
        user_message=request.message,
        user_id=current_user.sub,
        session_id=session_id,
        db=db,
        request_id=request_id,
    )

    if final_state.get("error"):
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to generate a coaching response. Please try again.",
        )

    return ChatResponse(
        response=final_state.get("final_response", ""),
        session_id=session_id,
        agent_trace=final_state.get("agent_trace", []),
        follow_up_suggestions=final_state.get("follow_up_suggestions", []),
        confidence_score=final_state.get("confidence_score"),
        request_id=request_id,
    )


class ConversationHistoryResponse(BaseModel):
    messages: list[dict]
    session_id: str
    total_count: int


@router.get("/history/{session_id}", response_model=ConversationHistoryResponse)
async def get_conversation_history(
    session_id: str,
    current_user: TokenPayload = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
    limit: int = 50,
    offset: int = 0,
) -> ConversationHistoryResponse:
    """Retrieve conversation history for a session."""
    from sqlalchemy import select
    from app.db.models.memory import ConversationMessage
    from app.db.models.user import User

    result = await db.execute(
        select(ConversationMessage)
        .join(User, ConversationMessage.user_id == User.id)
        .where(
            User.clerk_user_id == current_user.sub,
            ConversationMessage.session_id == session_id,
        )
        .order_by(ConversationMessage.created_at.asc())
        .offset(offset)
        .limit(limit)
    )
    messages = result.scalars().all()

    return ConversationHistoryResponse(
        messages=[
            {
                "id": str(msg.id),
                "role": msg.role,
                "content": msg.content,
                "agent_name": msg.agent_name,
                "created_at": msg.created_at.isoformat(),
            }
            for msg in messages
        ],
        session_id=session_id,
        total_count=len(messages),
    )
